version: '3'
services:
  app:
    build: 
      context: .
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./cmd:/work/cmd
      - ./internal:/work/internal
      - ./migrations:/work/migrations
    ports:
      - "9001:9001"
    env_file: .env
    environment:
      - DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=chatapp
    ports:
      - '5434:5434'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    