// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/repositories.go

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	messages_dto "chatapp/internal/dto/messages"
	user_dto "chatapp/internal/dto/user"
	chat "chatapp/internal/entities/chat"
	users "chatapp/internal/entities/users"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepositoryInterface is a mock of UserRepositoryInterface interface.
type MockUserRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInterfaceMockRecorder
}

// MockUserRepositoryInterfaceMockRecorder is the mock recorder for MockUserRepositoryInterface.
type MockUserRepositoryInterfaceMockRecorder struct {
	mock *MockUserRepositoryInterface
}

// NewMockUserRepositoryInterface creates a new mock instance.
func NewMockUserRepositoryInterface(ctrl *gomock.Controller) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepositoryInterface) Create(ctx context.Context, userDto *user_dto.CreateUserDTO) (*users.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userDto)
	ret0, _ := ret[0].(*users.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryInterfaceMockRecorder) Create(ctx, userDto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepositoryInterface)(nil).Create), ctx, userDto)
}

// GetUserByEmail mocks base method.
func (m *MockUserRepositoryInterface) GetUserByEmail(ctx context.Context, email string) (*users.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*users.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetUserByEmail), ctx, email)
}

// GetUserById mocks base method.
func (m *MockUserRepositoryInterface) GetUserById(ctx context.Context, id users.UserId) (*users.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, id)
	ret0, _ := ret[0].(*users.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetUserById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetUserById), ctx, id)
}

// MockConversationRepositoryInterface is a mock of ConversationRepositoryInterface interface.
type MockConversationRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockConversationRepositoryInterfaceMockRecorder
}

// MockConversationRepositoryInterfaceMockRecorder is the mock recorder for MockConversationRepositoryInterface.
type MockConversationRepositoryInterfaceMockRecorder struct {
	mock *MockConversationRepositoryInterface
}

// NewMockConversationRepositoryInterface creates a new mock instance.
func NewMockConversationRepositoryInterface(ctrl *gomock.Controller) *MockConversationRepositoryInterface {
	mock := &MockConversationRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockConversationRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversationRepositoryInterface) EXPECT() *MockConversationRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockConversationRepositoryInterface) Create(ctx context.Context, cnv *chat.Conversation, pts []users.UserId) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cnv, pts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockConversationRepositoryInterfaceMockRecorder) Create(ctx, cnv, pts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConversationRepositoryInterface)(nil).Create), ctx, cnv, pts)
}

// GetConversationById mocks base method.
func (m *MockConversationRepositoryInterface) GetConversationById(ctx context.Context, cnvId int64) (*chat.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversationById", ctx, cnvId)
	ret0, _ := ret[0].(*chat.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversationById indicates an expected call of GetConversationById.
func (mr *MockConversationRepositoryInterfaceMockRecorder) GetConversationById(ctx, cnvId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversationById", reflect.TypeOf((*MockConversationRepositoryInterface)(nil).GetConversationById), ctx, cnvId)
}

// GetParticipants mocks base method.
func (m *MockConversationRepositoryInterface) GetParticipants(ctx context.Context, cnvId int64) ([]*chat.ConversationParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParticipants", ctx, cnvId)
	ret0, _ := ret[0].([]*chat.ConversationParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipants indicates an expected call of GetParticipants.
func (mr *MockConversationRepositoryInterfaceMockRecorder) GetParticipants(ctx, cnvId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipants", reflect.TypeOf((*MockConversationRepositoryInterface)(nil).GetParticipants), ctx, cnvId)
}

// IsConversationExists mocks base method.
func (m *MockConversationRepositoryInterface) IsConversationExists(ctx context.Context, cnvId int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConversationExists", ctx, cnvId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsConversationExists indicates an expected call of IsConversationExists.
func (mr *MockConversationRepositoryInterfaceMockRecorder) IsConversationExists(ctx, cnvId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConversationExists", reflect.TypeOf((*MockConversationRepositoryInterface)(nil).IsConversationExists), ctx, cnvId)
}

// IsParticipant mocks base method.
func (m *MockConversationRepositoryInterface) IsParticipant(ctx context.Context, cnvId int64, usrId users.UserId) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsParticipant", ctx, cnvId, usrId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsParticipant indicates an expected call of IsParticipant.
func (mr *MockConversationRepositoryInterfaceMockRecorder) IsParticipant(ctx, cnvId, usrId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsParticipant", reflect.TypeOf((*MockConversationRepositoryInterface)(nil).IsParticipant), ctx, cnvId, usrId)
}

// MockMessageRepositoryInterface is a mock of MessageRepositoryInterface interface.
type MockMessageRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryInterfaceMockRecorder
}

// MockMessageRepositoryInterfaceMockRecorder is the mock recorder for MockMessageRepositoryInterface.
type MockMessageRepositoryInterfaceMockRecorder struct {
	mock *MockMessageRepositoryInterface
}

// NewMockMessageRepositoryInterface creates a new mock instance.
func NewMockMessageRepositoryInterface(ctrl *gomock.Controller) *MockMessageRepositoryInterface {
	mock := &MockMessageRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepositoryInterface) EXPECT() *MockMessageRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMessageRepositoryInterface) Create(ctx context.Context, message *chat.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMessageRepositoryInterfaceMockRecorder) Create(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessageRepositoryInterface)(nil).Create), ctx, message)
}

// GetMessageById mocks base method.
func (m *MockMessageRepositoryInterface) GetMessageById(ctx context.Context, convId, msgId int64) (*chat.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageById", ctx, convId, msgId)
	ret0, _ := ret[0].(*chat.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageById indicates an expected call of GetMessageById.
func (mr *MockMessageRepositoryInterfaceMockRecorder) GetMessageById(ctx, convId, msgId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageById", reflect.TypeOf((*MockMessageRepositoryInterface)(nil).GetMessageById), ctx, convId, msgId)
}

// GetMessages mocks base method.
func (m *MockMessageRepositoryInterface) GetMessages(ctx context.Context, qParams *messages_dto.GetMessageQueryParams) ([]*chat.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, qParams)
	ret0, _ := ret[0].([]*chat.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockMessageRepositoryInterfaceMockRecorder) GetMessages(ctx, qParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockMessageRepositoryInterface)(nil).GetMessages), ctx, qParams)
}

// Update mocks base method.
func (m *MockMessageRepositoryInterface) Update(ctx context.Context, msg *chat.Message, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, msg, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMessageRepositoryInterfaceMockRecorder) Update(ctx, msg, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMessageRepositoryInterface)(nil).Update), ctx, msg, content)
}
