// Code generated by MockGen. DO NOT EDIT.
// Source: internal/eventListeners/eventListeners.go

// Package mock_eventlisteners is a generated GoMock package.
package mock_eventlisteners

import (
	chat "chatapp/internal/entities/chat"
	users "chatapp/internal/entities/users"
	events "chatapp/internal/services/events"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIChatEventListener is a mock of IChatEventListener interface.
type MockIChatEventListener struct {
	ctrl     *gomock.Controller
	recorder *MockIChatEventListenerMockRecorder
}

// MockIChatEventListenerMockRecorder is the mock recorder for MockIChatEventListener.
type MockIChatEventListenerMockRecorder struct {
	mock *MockIChatEventListener
}

// NewMockIChatEventListener creates a new mock instance.
func NewMockIChatEventListener(ctrl *gomock.Controller) *MockIChatEventListener {
	mock := &MockIChatEventListener{ctrl: ctrl}
	mock.recorder = &MockIChatEventListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIChatEventListener) EXPECT() *MockIChatEventListenerMockRecorder {
	return m.recorder
}

// PostMessageCreated mocks base method.
func (m *MockIChatEventListener) PostMessageCreated(msg *chat.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PostMessageCreated", msg)
}

// PostMessageCreated indicates an expected call of PostMessageCreated.
func (mr *MockIChatEventListenerMockRecorder) PostMessageCreated(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostMessageCreated", reflect.TypeOf((*MockIChatEventListener)(nil).PostMessageCreated), msg)
}

// PostMessageUpdated mocks base method.
func (m *MockIChatEventListener) PostMessageUpdated(msg *chat.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PostMessageUpdated", msg)
}

// PostMessageUpdated indicates an expected call of PostMessageUpdated.
func (mr *MockIChatEventListenerMockRecorder) PostMessageUpdated(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostMessageUpdated", reflect.TypeOf((*MockIChatEventListener)(nil).PostMessageUpdated), msg)
}

// PostUserTyping mocks base method.
func (m *MockIChatEventListener) PostUserTyping(cnvId int64, usrId users.UserId) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PostUserTyping", cnvId, usrId)
}

// PostUserTyping indicates an expected call of PostUserTyping.
func (mr *MockIChatEventListenerMockRecorder) PostUserTyping(cnvId, usrId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostUserTyping", reflect.TypeOf((*MockIChatEventListener)(nil).PostUserTyping), cnvId, usrId)
}

// SubscribeChannel mocks base method.
func (m *MockIChatEventListener) SubscribeChannel(convId int64, l chan<- events.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SubscribeChannel", convId, l)
}

// SubscribeChannel indicates an expected call of SubscribeChannel.
func (mr *MockIChatEventListenerMockRecorder) SubscribeChannel(convId, l interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeChannel", reflect.TypeOf((*MockIChatEventListener)(nil).SubscribeChannel), convId, l)
}

// UnsubscribeChannel mocks base method.
func (m *MockIChatEventListener) UnsubscribeChannel(convId int64, l chan<- events.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnsubscribeChannel", convId, l)
}

// UnsubscribeChannel indicates an expected call of UnsubscribeChannel.
func (mr *MockIChatEventListenerMockRecorder) UnsubscribeChannel(convId, l interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeChannel", reflect.TypeOf((*MockIChatEventListener)(nil).UnsubscribeChannel), convId, l)
}
