name: Test GCP Auth

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker --quiet
      - name: Print Project
        run: |
          gcloud config list project
      - name:  Build & Push to GCR
        run: |
          echo "Pushing to GCR"
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/server:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/server:${{ github.sha }}