name: Test GCP Auth

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: GCP Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name: Print Project
        run: |
          gcloud config list project
      - name:  Build & Push to GCR
        run: |
          echo "Pushing to GCR"
          IMAGE=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-docker-repo/server:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE