name: Test GCP Auth

on: ['push']

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          token_format: access_token
          scopes: https://www.googleapis.com/auth/cloud-platform
      - name: Print Project
        run: |
          gcloud config list project
